### ISSUE TITLE
Clicking "auto" before app is loaded prevents auto mode from working

### ISSUE THREAD

**Issue by cliffrowley** [leeola/appaid.kdapp#11]
Although it's easy to work around and is low priority, I figured I'd report it anyway.

If you click "Auto" in the "Auto / Manual" button bar before an app has actually been loaded the "Auto" button is selected, suggesting that auto mode is enabled - however once an app is loaded it's clear that it is not.

Steps to reproduce:
1. Run AppAid
2. Click "Auto" in the "Auto / Manual" button bar
3. Load an app
4. Make a change and save
5. Observe that app is not compiled and reloaded

Workaround is pretty simple, just click "Manual" and then "Auto" again.

**Comment by leeola** [comment]
This is a throwback to a "i don't know" bug lol.

This issue exists because of this line:
https://github.com/leeolayvar/appaid.kdapp/blob/master/app/views.coffee#L101

I tried setting the compile toggle back to manual, but everything froze, badly. I need to figure out how to toggle the value back to what i want.

**Comment by cliffrowley** [comment]
I wonder if it's perhaps just easier to hide or disable the rest of the toolbar controls until an app is loaded?

**Comment by leeola** [comment]
It would be easiest if the damn button didn't explode Koding when i used `setValue()` lol, but nevertheless hiding the buttons might be a good idea for future features

**Comment by leeola** [comment]
I've got it figured out, not sure why i didn't think of it before. setValue() is triggering the callback, so using a dynamic setValue in the callback is suicide lol.

**Comment by leeola** [comment]
Let me know how this works for you (it's in the develop branch) and if there are any quirks. I hastily added it.

I would have preferred to _disable_ the UI when no app is loaded, but it didn't seem to be working for me at the time. So for now i'm just hiding/showing them.
