### ISSUE TITLE
Remove title banner

### ISSUE THREAD

**Issue by cliffrowley** [leeola/appaid.kdapp#9]
Is there any chance you might remove the "AppAid: Make your KDApps Faster and Easier!" title from the app?  Two reasons:
1. It interferes with the design of the app under development.  You could say that the buttons on the right hand side of the toolbar are also a distraction, but I think that they are acceptable - whereas I think the banner text is actually quite detrimental when an app is already text heavy.  For example, see [this screenshot](http://d.pr/i/IbWa/2OEz5kjf).
2. It actually might be confusing for inexperienced users anyway as the phrasing could easily be misinterpreted as "Make your apps perform faster" rather than "Make the process of developing apps more efficient".

**Comment by leeola** [comment]
1. So you think a blank bar on the left side would be more helpful? I would agree that it can get a bit confusing, but i'm not sure how to clear that up with the user. I tried to make sure that visually, there was a separated section (background colors/etc), but i'm not sure how best to resolve this
2. I agree with, it's pulled from the manifest so i think the whole description should be changed.

**Comment by cliffrowley** [comment]
Yeah, I think the bar being blank on the left hand side would definitely be clearer.  I don't think the user really needs to be constantly reminded what AppAid is or what it does, because they've installed it and are using it for its purpose already ;-) 
On 4 September 2013 at 15:13:34, Lee Olayvar (notifications@github.com) wrote:

So you think a blank bar on the left side would be more helpful? I would agree that it can get a bit confusing, but i'm not sure how to clear that up with the user. I tried to make sure that visually, there was a separated section (background colors/etc), but i'm not sure how best to resolve this

I agree with, it's pulled from the manifest so i think the whole description should be changed.

**Comment by leeola** [comment]
Sidenote, you mentioned you would like the whole bar gone, where would you put the information?

**Comment by leeola** [comment]
.. bah, i'm not awake. :P

**Comment by cliffrowley** [comment]
Oh I never said the whole bar should go - or at least that wasn't my intention.  Just the left hand text, which really just serves as UI noise / clutter :-) 
On 4 September 2013 at 15:27:34, Lee Olayvar (notifications@github.com) wrote:

Sidenote, you mentioned you would like the whole bar gone, where would you put the information?

**Comment by leeola** [comment]
Hmm, odd, not sure why this didn't get closed from my commit message. I wonder if it only closes automatically when the commit is merged into the "default" github branch (master)
